# Generated by Django 5.0.7 on 2024-07-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200904_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dateissued',
            field=models.DateField(help_text='Date staff ID was issued', null=True, verbose_name='Date Issued'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, default='default.png', help_text='Upload image size less than 2.0MB', null=True, upload_to='profiles', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Button to toggle employee block and unblock', verbose_name='Is Blocked'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Button to toggle employee deleted and undelete', verbose_name='Is Deleted'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='startdate',
            field=models.DateField(help_text='Date of employment', null=True, verbose_name='Employment Date'),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
