# Generated by Django 5.0.7 on 2024-08-02 05:24

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_delete_religion_alter_department_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name', 'created'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='nationality',
            options={'ordering': ['name'], 'verbose_name': 'Nationality', 'verbose_name_plural': 'Nationalities'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name', 'created'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='created',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='description',
        ),
        migrations.RemoveField(
            model_name='nationality',
            name='updated',
        ),
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(default=datetime.date.today, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='nationality',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dateissued',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date Issued'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeid',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Employee ID Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeetype',
            field=models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='Full-Time', max_length=15, verbose_name='Employee Type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(max_length=125, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.FileField(blank=True, default='default.png', help_text='Upload image size less than 2.0MB', null=True, upload_to='profiles', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Is Blocked'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(max_length=125, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='othername',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Othername (optional)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.role', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='startdate',
            field=models.DateField(default=django.utils.timezone.now, help_text='date of employment', verbose_name='Employement Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated'),
        ),
    ]
