# Generated by Django 5.0.7 on 2024-08-02 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_alter_leave_defaultdays_alter_leave_enddate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='defaultdays',
            field=models.PositiveIntegerField(blank=True, default=30, null=True, verbose_name='Leave days per year counter'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='enddate',
            field=models.DateField(help_text='coming back on ...', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(choices=[('sick', 'Sick Leave'), ('casual', 'Casual Leave'), ('emergency', 'Emergency Leave'), ('study', 'Study Leave'), ('maternity', 'Maternity Leave'), ('bereavement', 'Bereavement Leave'), ('quarantine', 'Self Quarantine'), ('compensatory', 'Compensatory Leave'), ('sabbatical', 'Sabbatical Leave')], default='sick', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(blank=True, help_text='add additional information for leave', max_length=255, null=True, verbose_name='Reason for Leave'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='startdate',
            field=models.DateField(help_text='leave start date is on ..', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
